### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shitou520** [RocFang/nginx-rtmp-module-wiki-ZH#1]
试问nginx-rtmp存在哪些大量bug？只是某些功能不支持而已。开源软件哪个不是需要拿来修改的。

**Comment by RocFang** [comment]
晕，我这句话有问题吗？
我自然是发现和解决了大量bug才这么说的。如果你没发现，那只是你在某些方面走的不够远而已。

**Comment by RocFang** [comment]
> 开源软件哪个不是需要拿来修改的。

这个跟它存在大量bug没有矛盾吧？而且我前提也说了，这是个非常非常优秀的服务器，总而言之，不明白你想说什么。

**Comment by shitou520** [comment]
那把你解决了哪些bug列出来分享下。
